// <auto-generated />
using System;
using InvoiceDesigner.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceDesigner.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefaultVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentTerms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WWW")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "US Dollar",
                            IsDeleted = false,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Euro",
                            IsDeleted = false,
                            Name = "EUR"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Czech Koruna",
                            IsDeleted = false,
                            Name = "CZK"
                        });
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VatId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnabledVat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Vat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.CssStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DropItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DropItemId");

                    b.ToTable("DropItemStyles");

                    b.HasData(
                        new
                        {
                            Id = 5925,
                            DropItemId = 967,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5926,
                            DropItemId = 967,
                            Name = "text-align",
                            Value = "center"
                        },
                        new
                        {
                            Id = 5927,
                            DropItemId = 967,
                            Name = "font-size",
                            Value = "16px"
                        },
                        new
                        {
                            Id = 5928,
                            DropItemId = 967,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5929,
                            DropItemId = 967,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5930,
                            DropItemId = 967,
                            Name = "font-weight",
                            Value = "bold"
                        },
                        new
                        {
                            Id = 5931,
                            DropItemId = 968,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5932,
                            DropItemId = 968,
                            Name = "text-align",
                            Value = "right"
                        },
                        new
                        {
                            Id = 5933,
                            DropItemId = 968,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5934,
                            DropItemId = 968,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5935,
                            DropItemId = 968,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5936,
                            DropItemId = 968,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5937,
                            DropItemId = 969,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5938,
                            DropItemId = 969,
                            Name = "text-align",
                            Value = "right"
                        },
                        new
                        {
                            Id = 5939,
                            DropItemId = 969,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5940,
                            DropItemId = 969,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5941,
                            DropItemId = 969,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5942,
                            DropItemId = 969,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5943,
                            DropItemId = 970,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5944,
                            DropItemId = 970,
                            Name = "text-align",
                            Value = "right"
                        },
                        new
                        {
                            Id = 5945,
                            DropItemId = 970,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5946,
                            DropItemId = 970,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5947,
                            DropItemId = 970,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5948,
                            DropItemId = 970,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5949,
                            DropItemId = 971,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5950,
                            DropItemId = 971,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5951,
                            DropItemId = 971,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5952,
                            DropItemId = 971,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5953,
                            DropItemId = 971,
                            Name = "font-style",
                            Value = "italic"
                        },
                        new
                        {
                            Id = 5954,
                            DropItemId = 971,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5955,
                            DropItemId = 971,
                            Name = "AddCurrencySymbol",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5956,
                            DropItemId = 971,
                            Name = "AddCurrencySymbolFooter",
                            Value = "right"
                        },
                        new
                        {
                            Id = 5957,
                            DropItemId = 972,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5958,
                            DropItemId = 972,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5959,
                            DropItemId = 972,
                            Name = "font-size",
                            Value = "12px"
                        },
                        new
                        {
                            Id = 5960,
                            DropItemId = 972,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5961,
                            DropItemId = 972,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5962,
                            DropItemId = 972,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5963,
                            DropItemId = 973,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5964,
                            DropItemId = 973,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5965,
                            DropItemId = 973,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5966,
                            DropItemId = 973,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5967,
                            DropItemId = 973,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5968,
                            DropItemId = 973,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5969,
                            DropItemId = 974,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5970,
                            DropItemId = 974,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5971,
                            DropItemId = 974,
                            Name = "font-size",
                            Value = "12px"
                        },
                        new
                        {
                            Id = 5972,
                            DropItemId = 974,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5973,
                            DropItemId = 974,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5974,
                            DropItemId = 974,
                            Name = "font-weight",
                            Value = "bold"
                        },
                        new
                        {
                            Id = 5975,
                            DropItemId = 975,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5976,
                            DropItemId = 975,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5977,
                            DropItemId = 975,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5978,
                            DropItemId = 975,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5979,
                            DropItemId = 975,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5980,
                            DropItemId = 975,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5981,
                            DropItemId = 976,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5982,
                            DropItemId = 976,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5983,
                            DropItemId = 976,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5984,
                            DropItemId = 976,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5985,
                            DropItemId = 976,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5986,
                            DropItemId = 976,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5987,
                            DropItemId = 977,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5988,
                            DropItemId = 977,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 5989,
                            DropItemId = 977,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5990,
                            DropItemId = 977,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5991,
                            DropItemId = 977,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5992,
                            DropItemId = 977,
                            Name = "font-weight",
                            Value = "bold"
                        },
                        new
                        {
                            Id = 5993,
                            DropItemId = 978,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 5994,
                            DropItemId = 978,
                            Name = "text-align",
                            Value = "center"
                        },
                        new
                        {
                            Id = 5995,
                            DropItemId = 978,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 5996,
                            DropItemId = 978,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 5997,
                            DropItemId = 978,
                            Name = "font-style",
                            Value = "italic"
                        },
                        new
                        {
                            Id = 5998,
                            DropItemId = 978,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 5999,
                            DropItemId = 979,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 6000,
                            DropItemId = 979,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 6001,
                            DropItemId = 979,
                            Name = "font-size",
                            Value = "12px"
                        },
                        new
                        {
                            Id = 6002,
                            DropItemId = 979,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 6003,
                            DropItemId = 979,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 6004,
                            DropItemId = 979,
                            Name = "font-weight",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 6005,
                            DropItemId = 980,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 6006,
                            DropItemId = 980,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 6007,
                            DropItemId = 980,
                            Name = "font-size",
                            Value = "12px"
                        },
                        new
                        {
                            Id = 6008,
                            DropItemId = 980,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 6009,
                            DropItemId = 980,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 6010,
                            DropItemId = 980,
                            Name = "font-weight",
                            Value = "bold"
                        },
                        new
                        {
                            Id = 6011,
                            DropItemId = 981,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 6012,
                            DropItemId = 981,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 6013,
                            DropItemId = 981,
                            Name = "font-size",
                            Value = "12px"
                        },
                        new
                        {
                            Id = 6014,
                            DropItemId = 981,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 6015,
                            DropItemId = 981,
                            Name = "font-style",
                            Value = "normal"
                        },
                        new
                        {
                            Id = 6016,
                            DropItemId = 981,
                            Name = "font-weight",
                            Value = "bold"
                        },
                        new
                        {
                            Id = 6017,
                            DropItemId = 982,
                            Name = "flex-grow",
                            Value = "1"
                        },
                        new
                        {
                            Id = 6018,
                            DropItemId = 982,
                            Name = "text-align",
                            Value = "left"
                        },
                        new
                        {
                            Id = 6019,
                            DropItemId = 982,
                            Name = "font-size",
                            Value = "10px"
                        },
                        new
                        {
                            Id = 6020,
                            DropItemId = 982,
                            Name = "height",
                            Value = "25px"
                        },
                        new
                        {
                            Id = 6021,
                            DropItemId = 982,
                            Name = "font-style",
                            Value = "italic"
                        },
                        new
                        {
                            Id = 6022,
                            DropItemId = 982,
                            Name = "font-weight",
                            Value = "normal"
                        });
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.DropItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormDesignerSchemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartSelector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormDesignerSchemeId");

                    b.ToTable("DropItems");

                    b.HasData(
                        new
                        {
                            Id = 967,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_0_0",
                            StartSelector = "_Invoice",
                            UniqueId = "{Invoice.InvoiceNumber}",
                            Value = "Invoice #{Invoice.InvoiceNumber}"
                        },
                        new
                        {
                            Id = 968,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_1_2",
                            StartSelector = "_Invoice",
                            UniqueId = "{Invoice.DateTime}",
                            Value = "Issue Date: {Invoice.DateTime}"
                        },
                        new
                        {
                            Id = 969,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_2_2",
                            StartSelector = "_Invoice",
                            UniqueId = "{Invoice.DueDate}",
                            Value = "Due Date: {Invoice.DueDate}"
                        },
                        new
                        {
                            Id = 970,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_3_2",
                            StartSelector = "_Invoice",
                            UniqueId = "{Invoice.PONumber}",
                            Value = "PO: {Invoice.PONumber}"
                        },
                        new
                        {
                            Id = 971,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_11_0",
                            StartSelector = "_Invoice",
                            UniqueId = "{Invoice.InvoiceItems}",
                            Value = "{Invoice.InvoiceItems}"
                        },
                        new
                        {
                            Id = 972,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_5_2",
                            StartSelector = "_Customer",
                            UniqueId = "{Customer.Name}",
                            Value = "{Customer.Name}"
                        },
                        new
                        {
                            Id = 973,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_6_2",
                            StartSelector = "_Customer",
                            UniqueId = "{Customer.TaxId}",
                            Value = "Tax ID: {Customer.TaxId}"
                        },
                        new
                        {
                            Id = 974,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_2_0",
                            StartSelector = "_Company",
                            UniqueId = "{Company.Name}",
                            Value = "{Company.Name}"
                        },
                        new
                        {
                            Id = 975,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_3_0",
                            StartSelector = "_Company",
                            UniqueId = "{Company.TaxId}",
                            Value = "Tax ID: {Company.TaxId}"
                        },
                        new
                        {
                            Id = 976,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_4_0",
                            StartSelector = "_Company",
                            UniqueId = "{Company.VatId}",
                            Value = "Vat ID: {Company.VatId}"
                        },
                        new
                        {
                            Id = 977,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_4_2",
                            StartSelector = "_Other",
                            UniqueId = "c09e7e7f-1700-4eb7-b83e-4e9b0be08e66",
                            Value = "Bill  To:"
                        },
                        new
                        {
                            Id = 978,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_15_0",
                            StartSelector = "_Other",
                            UniqueId = "ebd7a5ce-37fc-4d21-9651-38390fb4fd69",
                            Value = "Karel Kalata"
                        },
                        new
                        {
                            Id = 979,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_5_0",
                            StartSelector = "_Bank",
                            UniqueId = "{Bank.Name}",
                            Value = "Bank: {Bank.Name}"
                        },
                        new
                        {
                            Id = 980,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_6_0",
                            StartSelector = "_Bank",
                            UniqueId = "{Bank.BIC}",
                            Value = "BIC/SWIFT: {Bank.BIC}"
                        },
                        new
                        {
                            Id = 981,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_7_0",
                            StartSelector = "_Bank",
                            UniqueId = "{Bank.Account}",
                            Value = "{Bank.Account}"
                        },
                        new
                        {
                            Id = 982,
                            FormDesignerSchemeId = 1,
                            Selector = "coor_9_0",
                            StartSelector = "_Other",
                            UniqueId = "ec235007-1e77-4be7-9e87-c7552fb9776a",
                            Value = "If you have any questions, please contact us at {Company.Phone} or {Company.Email}"
                        });
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.FormDesigner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FormDesigners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "default"
                        });
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.FormDesignerScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Column")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormDesignerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormDesignerId");

                    b.ToTable("FormDesignerSchemes");

                    b.HasData(
                        new
                        {
                            Id = 2465,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 0
                        },
                        new
                        {
                            Id = 2466,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 1
                        },
                        new
                        {
                            Id = 2467,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 2
                        },
                        new
                        {
                            Id = 2468,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 3
                        },
                        new
                        {
                            Id = 2469,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 4
                        },
                        new
                        {
                            Id = 2470,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 5
                        },
                        new
                        {
                            Id = 2471,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 6
                        },
                        new
                        {
                            Id = 2472,
                            Column = 2,
                            FormDesignerId = 1,
                            Row = 7
                        },
                        new
                        {
                            Id = 2473,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 8
                        },
                        new
                        {
                            Id = 2474,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 9
                        },
                        new
                        {
                            Id = 2475,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 10
                        },
                        new
                        {
                            Id = 2476,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 11
                        },
                        new
                        {
                            Id = 2477,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 12
                        },
                        new
                        {
                            Id = 2478,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 13
                        },
                        new
                        {
                            Id = 2479,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 14
                        },
                        new
                        {
                            Id = 2480,
                            Column = 1,
                            FormDesignerId = 1,
                            Row = 15
                        },
                        new
                        {
                            Id = 2481,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 16
                        },
                        new
                        {
                            Id = 2482,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 17
                        },
                        new
                        {
                            Id = 2483,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 18
                        },
                        new
                        {
                            Id = 2484,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 19
                        },
                        new
                        {
                            Id = 2485,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 20
                        },
                        new
                        {
                            Id = 2486,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 21
                        },
                        new
                        {
                            Id = 2487,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 22
                        },
                        new
                        {
                            Id = 2488,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 23
                        },
                        new
                        {
                            Id = 2489,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 24
                        },
                        new
                        {
                            Id = 2490,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 25
                        },
                        new
                        {
                            Id = 2491,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 26
                        },
                        new
                        {
                            Id = 2492,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 27
                        },
                        new
                        {
                            Id = 2493,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 28
                        },
                        new
                        {
                            Id = 2494,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 29
                        },
                        new
                        {
                            Id = 2495,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 30
                        },
                        new
                        {
                            Id = 2496,
                            Column = 0,
                            FormDesignerId = 1,
                            Row = 31
                        });
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.PrintInvoice", b =>
                {
                    b.Property<Guid>("Giud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrintFormId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Giud");

                    b.ToTable("PrintInvoices");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrice");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Login = "admin",
                            Name = "Super Admin",
                            PasswordHash = "1708D30988E562DD2958B50B77F0D61C47C59FD7555F3B91AB02D486F361504F7E0C569157D104D99E5076BFF20AF9EE38482A63BA10993B28C38F9936668010",
                            PasswordSalt = "7A6604F49A4E8EFCBB8B6CA86305FB0E4E14F817AE6D8726DE7A56463581A1D21D68699970298BBFE2182AE02366BCBB56C14DF47B9D000AF0C5D74DCED88953"
                        });
                });

            modelBuilder.Entity("UserCompany", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompanyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompany");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Bank", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Company", "Company")
                        .WithMany("Banks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Company", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Invoice", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Company");

                    b.Navigation("Currency");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.InvoiceItem", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.CssStyle", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.DropItem", "DropItem")
                        .WithMany("CssStyle")
                        .HasForeignKey("DropItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DropItem");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.DropItem", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.FormDesigner", null)
                        .WithMany("DropItems")
                        .HasForeignKey("FormDesignerSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.FormDesignerScheme", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.FormDesigner", null)
                        .WithMany("Schemes")
                        .HasForeignKey("FormDesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ProductPrice", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Product", null)
                        .WithMany("ProductPrice")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("UserCompany", b =>
                {
                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceDesigner.Domain.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Company", b =>
                {
                    b.Navigation("Banks");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.DropItem", b =>
                {
                    b.Navigation("CssStyle");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.ModelsFormDesigner.FormDesigner", b =>
                {
                    b.Navigation("DropItems");

                    b.Navigation("Schemes");
                });

            modelBuilder.Entity("InvoiceDesigner.Domain.Shared.Models.Product", b =>
                {
                    b.Navigation("ProductPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
